NYCPlanning/db-factfinder

factfinder/aggregate_geography.py, factfinder/main.py
- aggregate_nta -> tract_to_nta
- aggergate_fp500 -> block_group_to_cd_fp500
- creating tract_to_cd
this is necessary because for decennial we do aggregation from blocks to nta, it would be confusing if we just have "aggregate_nta"
=> be more verbose about aggregation functions

factfinder/main.py
- remove dependent variables from median calculation
- use a dictionary to provide clarity for geographic aggregation
=> simplify aggregate_vertical

factfinder/data/metadata.json, factfinder/main.py
=> Add comments and set base for pop2010

.github/workflows/acs.yml
- will run on push
- need to change name `demographic.py` to `build.py`
=> creating github actions for acs

factfinder/main.py
=> 37 type safety

README.md
Update ReadMe to reflect new user interface
=> Switch from calculate_variable to calculate

factfinder/data/metadata.json
#46 
For use with: https://github.com/NYCPlanning/db-community-profiles/pull/45
Mapping based on: https://github.com/NYCPlanning/db-community-profiles/issues/43
=> Add variables for cdp floodplain calulations

setup.py
Include `package_data` and `include_package_data` arguments in setup function.
=> Package data files

factfinder/main.py
=> remove line 378, avoid double calculation

factfinder/data/special.json, factfinder/special.py
=> define wrkrNotHm as a special variable

factfinder/main.py
#69 
#56 
also increasing cache size
=> hardcoding special variable exceptions

factfinder/data/acs/2018/metadata.json, factfinder/main.py
=> Add calculate_poverty_p_z and implementation

pipelines/acs/build.py, poetry.lock, pyproject.toml
+ Currently is not using multiprocessing
=> Switch to loop and add progress bar

factfinder/data/acs/2018/metadata.json, factfinder/data/acs/2019/metadata.json, factfinder/data/decennial/2010/metadata.json, pyproject.toml
=> Move decennial cdprofile vars to decennial metadata

factfinder/data/acs/2019/metadata.json
See intermediate files and code used in issue #97
=> Update metadata.json for 2019 variable mapping

factfinder/data/acs/2019/metadata.json
This should fix lgvielep1, r550t599
=> Fix metadata capitalization

factfinder/metadata.py, tests/test_metadata.py
Reverts NYCPlanning/db-factfinder#110
=> Revert "Metadata census variable method patch"

factfinder/calculate.py, factfinder/geography/2010.py, factfinder/geography/2010_to_2020.py, factfinder/utils.py, tests/test_calculate.py
=> Add labs geoid and geotype

factfinder/geography/2010_to_2020.py
Based on June 30 update [here](https://github.com/NYCPlanning/db-acs-2020/blob/main/raw/geo_crosswalks/Draft%202010%20CT%20to%202020%20CT%20Crosswalk%20with%20MOE%20calculations_06-28-21.xlsx).
=> Update 2010 to 2020 MOE calculation

factfinder/data/acs/2019/metadata.json
=> Fix three base vars

factfinder/data/acs/2019/metadata.json
=> Update census vars for moved variables

factfinder/calculate.py
=> Do not overwrite median p with 100 in cleaning

factfinder/calculate.py, factfinder/metadata.py
Useful for debugging (or eventually changing logic) to identify cases where only estimate is relevant for PFF.
=> Add list of median inputs

factfinder/data/acs/2019/metadata.json
#149 
I think I found all of them. We can double-check in EDM easily once merged & built.
=> Fix demographic domain

factfinder/data/acs/2019/metadata.json
=> Add 3 missing domain fixes

factfinder/utils.py, notebooks/median.ipynb
#158 
Also added comments since median calculation is fairly complicated to follow in the code.
=> Set C_l to 0 if lower bin is 0

factfinder/data/acs/2010/metadata.json, factfinder/data/acs/2019/metadata.json
=> fix rounding for 2019

factfinder/calculate.py, pipelines/acs.py, poetry.lock, pyproject.toml
this will reduce the run time to 19 min
=> Patch multiprocessing pathos

factfinder/data/acs/2019/metadata.json
=> Fix base variable for lgchilep2

factfinder/calculate.py
this should fix the remaining poverty variables mentioned in 
https://github.com/NYCPlanning/db-factfinder/issues/130#issuecomment-882735352
https://github.com/NYCPlanning/db-factfinder/issues/72
=> For aggregated geography we should calculate the P and Z for poverty vars

factfinder/data/acs/2010/metadata.json
#173 #172 
only awaiting poverty variable PE and PM mappings for city/borough level data
=> small fixes on metadata typos

factfinder/utils.py
this solves most of the MOE mismatches, there are still some remaining tho (79 records)....
=> Implement corner case for distributions that start with non-zeros

factfinder/data/acs/2010/metadata.json
https://github.com/NYCPlanning/db-acs-2020/pull/63/
running rn https://github.com/NYCPlanning/db-factfinder/actions/runs/1056372058
=> fixing hh1 related variables

factfinder/data/acs/2010/metadata.json
=> Fix zero padding in DP02 table

factfinder/data/acs/2010/metadata.json
=> Fix meta for popu18 variables

factfinder/data/acs/2010/metadata.json
=> Fix oeeur meta

factfinder/calculate.py, factfinder/median.py, notebooks/median.ipynb
Include case of same bin, first non-zero.
Also remove import of deleted util functions.
=> Implement same bin, first non-zero case

factfinder/geography/2010.py, factfinder/geography/2010_to_2020.py
Dependent on population's sign-off.
=> Ignore NULLs when aggregating MOE

.github/workflows/acs.yml, factfinder/median.py
1. ~~When upper_bin = lower_bin = first_non_zero_bin~~
2. the first_non_zero rule should never be apply to upper bound
=> Median MOE: Change lowest possible A1 val to 0.5 for mdrms

factfinder/calculate.py
=> if e==0, then everything else is np.nan

factfinder/data/acs/2010/metadata.json, factfinder/data/acs/2018/metadata.json, factfinder/data/acs/2019/metadata.json
=> Change median base variables to nan

.gitignore, factfinder/geography/2010_to_2020.py, geolookup/2020/build.sql, geolookup/2020/run.sh, geolookup/README.md, geolookup/__main__.py, geolookup/config.sh, pipelines/acs.py, pipelines/acs_community_profiles.py, pipelines/acs_community_profiles_variable_mapping.json
this is a simplified version of #108 
#108 was missing a lot of changes, so I'll manually cherry pick. 
Will merge after confirming that this change won't introduce more new errors. 
this PR will also add floodplain, park access data, so that we can use this package for community profiles data
=> Making sure 2010_to_2020 share the same lookup_geo, using official lookup geo

factfinder/calculate.py
fixes [AB#5025](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/5025)
=> Set p to 100 for all base variable for all geography level

.github/workflows/acs.yml, factfinder/data/acs/2010/metadata.json
[AB#5456](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/5456)
=> adding two more variables, only upload to s3 if we are on dev branch

pipelines/acs_2020_manual_update.py
Adds in Base Variable to output CSV to verify the mapping of PFF variables.
Renames Base Variable in existing script to PFF Variable to match this assumption.
=> PFF - Base Variable Mapping

pipelines/acs_2020_manual_update.py
Addresses #234 Review
Match the existing acs.csv format more closely by reordering and adding null columns
=> Add Census GeoID and GeoType columns to Output CSV

factfinder/data/acs/2020/metadata.json
Addresses #238 
Do any of the changes from the 2010 metadata need review here?
=> Update just the metadata files on dev from the Aug Branch

pipelines/acs_2020_manual_update.py
Addresses Issue #240 
Remove all code for attaching base variable. Once approved I can upload to digital ocean
=> Remove base variable from CSV

.github/workflows/acs.yml, .github/workflows/acs_community_profiles.yml, factfinder/data/acs/2020/metadata.json, pipelines/acs_community_profiles.py
- `main` is behind `dev` and there don't appear to be major in-progress work on `dev`
- maintaining a `dev` branch is expensive when the gains aren't significant
- there aren't many teams/people needing to merge breaking changes
- the QAQC app doesn't expect a dev branch (it isn't used on this repo at all)
- merge `dev` into `main`
- after merging, delete `dev` and use `main` as the default branch to simplify development and maintenance
=> merge dev into main and delete dev
