NYCPlanning/db-factfinder

- factfinder/aggregate_geography.py
- factfinder/data/metadata.json
- factfinder/main.py
- factfinder/variable.py
these are only used for median calculations, and we have a special handler for that
> removing ranges, median, design factor for metadata.json

- factfinder/main.py
#23 
- `profile_only_variables`
- splitting `download` into `download_e_m` and `download_e_m_p_z`
- adding a `download_function` to `download_variable`, this is needed so that we can pick which download function to use, and wrap it with multiprocessing
- adding `calculate_e_m_p_z` -> used by profile only variables for non-aggregated-geography
> Adding profile_only_variables property

- factfinder/data/metadata.json
- factfinder/main.py
- Change domain name from `demographics` to `demographic`
- fix calculate_e_m_p_z (list concatenation failed because we strictly limit calculate_e_m_p_z to only allow 1 census variable)
> change domain name and  fix errors

- pipelines/acs/README.md
- pipelines/acs/demographic.py
- setup.py
- adding a folder `pipelines`, while it makes sense to publish factfinder as a package and to be used by community profiles, it still makes sense to store pipelines for acs/decennial in this current repo
- the current set up is similar to rdptools, we have a python package in a folder and pipelines in another folder. also `pipelines` = `recipes` in this case
> adding local packaging and pipeline script example

- factfinder/main.py
This was decided through this issue: 
NYCPlanning/db-acs/issues/16
for estimates = 0, we should by default set moe = 0
remaining question: 
1. why
2. why not set moe = np.nan
> for e = 0, set moe = 0 by default

- factfinder/main.py
#41 
The proportion/proportion MOE should be 100/null for all base vars, regardless of geography.
> Set p to 100, z to null for all base var

- factfinder/data/metadata.json
#43 
Future language data for PFF will come from the collapsed 5-year table C16001. This table is similar to the previous source, but collapsed languages into larger categories. Population has yet to scope out the variables they want for each language category. Because the variable `lgoenlep1` is the sum of low-english proficiency across all non-English languages, we can create this variable for Community Profiles prior to mapping out all language variables for PFF.
This PR includes `lgoenlep1` and its associated base variable with domain `community_profiles` to use until we fully build out the replacement language variables for PFF.
> Add lgoenlep1 for community profiles

- factfinder/data/metadata.json
For community profiles, we pull total decennial population for both 2010 and 2000. This variable should not include versioning in its name.
> Change name of decennial population to not include date

- factfinder/main.py
#56 
To-do: change the base variables in the metadata to reflect DCP-preferred base.
> WIP: Restrict profile_only_variables to same base as pff_variable

- factfinder/main.py
#56
e.g. 
```json
{
"pff_variable": "abroad",
"base_variable": "dfhs2",
"census_variable": [
"DP02_0085"
],
"domain": "social",
"rounding": 0,
"source": "profile"
},
```
abroad should not be a profile only variable because pff_variable != base_variable, therefore cannot take PE/PM directly from census API
> profile only variable should have base_variable = pff_variable

- factfinder/main.py
The poverty variables do not have nan as a base. Only the percent-versions we use to fill in p and z have nan as a base.
> Move poverty p/z calc out of the nan base_variable logic

- factfinder/geography/2010_to_2020.py
CSV version of the [geog relationships](https://github.com/NYCPlanning/db-acs-2020/blob/main/lookups/geo_crosswalks/2020GeogRelate.xlsx) used to create sample output.
This version has fewer columns than the current, but I believe we only use tract-level for 2010 to 2020 calculations.
#151
> Use tract-level lookup-geo from Population

- factfinder/utils.py
- notebooks/median.ipynb
- pipelines/acs.py
#130 
This fixes cases where C = N/2 exactly for 2 successive ranges.
Testing here: https://github.com/NYCPlanning/db-factfinder/actions/runs/1046017255
> Switch to strictly less for while loop

- factfinder/data/acs/2010/metadata.json
this should address #153 
Script used to generate this file:
```python
import pandas as pd
import requests
import ast
import json
df = pd.read_csv('meta2010.csv')
df['census_variable'] = df['census_variable'].apply(ast.literal_eval)
df['rounding'] = df['rounding'].fillna('0').astype(int)
df['source'] = ''
df = df.loc[df.Notes != 'remove', ['pff_variable','census_variable', 'base_variable', 'domain', 'rounding', 'source']]
df_dict = df.to_dict('records')
with open('metadata.json', 'w') as f:
json.dump(df_dict, f, indent=4)
```
Running in github actions to test out results:
https://github.com/NYCPlanning/db-factfinder/actions/runs/1052808059
> adding acs 2006-2010 metadata mapping, received from erica

- factfinder/calculate.py
- factfinder/median.py
- notebooks/median.ipynb
- Check to make sure that upper bound is not in top bin before setting A2 in base case
- Use default np.nan in min functions
- Reset index after applying get_median_and_median_moe
- Fix divide-by-zero warning
> Fix empty list and geoid index error

- factfinder/data/acs/2010/metadata.json
- factfinder/data/acs/2018/metadata.json
- factfinder/data/acs/2019/metadata.json
To avoid calling these lines on 'mean':
https://github.com/NYCPlanning/db-factfinder/blob/41a7f2f9283de40e367f0332704d74a69c1cfd5a/factfinder/calculate.py#L258-L259
Because base of 'mean' passes:
https://github.com/NYCPlanning/db-factfinder/blob/41a7f2f9283de40e367f0332704d74a69c1cfd5a/factfinder/calculate.py#L245
I can't find anywhere else where a base of 'mean' determines calculation. Test once API is more stable before merging.
> Change 'mean' base vars to 'nan'

- factfinder/download.py
controlled variables so that cv is not null
> this is only the case for NYC and boroughs, in the data download these instances would appear as *****, it seems like in the API it is appearing in this case as "-555555555". This means the estimate is controlled. Rather than keeping the MOE null, we decided to show it as 0. This seems to be working sometimes in your code because the MOEs and percent MOEs are appearing as 0, but the CV is not calculated for some of these cases. I'm not sure the implementation step, but this issue of controlled estimates is only for NYC and boroughs.
CV is missing for ACS data where MOE=0 for NYC and boroughs. 
CV should equal 0. (Row should not be gray)
Check data:
2015-2019
PopU181: Brooklyn & Queens
Pop65pl: Queens
Pop65plM: Queens
Pop65plF: Queens
Hsp1: NYC …
> adding special outlier removal process for city/borough level

- pipelines/acs_2020_manual_update.py
Addresses issue #236. The source data is changed to excel file sent on Tuesday July 5th, and python code is changed to point to `<domain>_NonInflated` instead of `<domain>Inflated` for 2010 Econ and Housing.
Summary of changes to python code are mostly caused by Andrew and I using different linters, which we should definitely work out
> Ingest non inflated 2010 data

- .github/workflows/acs_2020_manual_update.yml
Addresses Issue #232 
Includes new Github Action for Pushing to Digital Ocean outputs of manual update scripts.
There may be an issue with getting a workflow dispatch to work on a non-main branch, unsure the correct workaround (beyond testing this with an on: push, which we could leave for this branch and just push both files)
> 232 upload ase output manual update to do

- factfinder/data/acs/2020/metadata.json
Addresses #242 
Will need a 2nd PR for the 221-Aug Build Branch, but from my understanding OSE is pulling from the metadata on this branch directly
> Update 2020 Metadata to add Base Variable for grpi20t24

- pipelines/acs_2020_manual_update.py
Addresses #243 
This reverts commit ef50b5bbdda619bdf0be5884f1b5f981bb753021.
When we removed the base variable join from the script, we removed any respect for the metadata file for 2010, and just piped through the input excel file. The excel file has columns for variables not in the metadata file, causing issues for OSE. Adds an inner join on the metadata file so we can only return records with a matching metadata.
Needs 2 Reviewers
> Remove ACS Variables from 2010 that don't match metadata file

- .github/workflows/acs_manual_update.yml
per ACS Update issue https://github.com/NYCPlanning/db-factfinder/issues/250 and in-progress PR #252 
- there's [an action from a dev branch](https://github.com/NYCPlanning/db-factfinder/actions/workflows/acs_2020_manual_update.yml) we'd like to use
- but we can't run it manually until it exists on the `main` branch
- this PR is just to add the action
> add manual update github action
